name: Build

on: [push, pull_request]

jobs:

  build:
    name: Ionic Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build --if-present

  build-android:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          ionic-version: 6

      - name: Sync Ionic with Android
        run: ionic cap sync

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build Debug APK
        run: cd android && bash ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: ${{ github.workspace }}/android/app/build/outputs/apk/debug/app-debug.apk