name: Build

on: [push, pull_request]

jobs:

  build:
    name: Ionic Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm ci
    - run: npm run build --if-present

  build-android:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install node modules
      run: npm install && npm run build
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        ionic-version: 6.19.1
    - name: Copy assets to Android
      run: ionic cap copy
    - name: Sync Ionic with Android
      run: ionic cap sync
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build Debug APK
      run: cd android && bash ./gradlew :app:assembleDebug
